version: '3'

services:
  php:
    environment:
      - XDEBUG_SESSION=docker-server
    build:
      ./php
    volumes:
      - ./:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "8081:80"